spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
      format-sql: true
  security:
    user:
      name: admin
      password: 1111