spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
      format-sql: true
  security:
    user:
      name: admin
      password: 1111
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: ${app.baseUrl}/login/oauth2/code/google
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${app.baseUrl}/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: profile_nickname, profile_image
            client-name: Kakao
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul
  vworld:
    api:
      key: ${VWORLD_API_KEY}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

# 네이버 설정 추가
naver:
  map:
    client-id: ${NAVER_MAP_CLIENT_ID}
    client-secret: ${NAVER_MAP_CLIENT_SECRET}
  search:
    client-id: ${NAVER_SEARCH_CLIENT_ID}
    client-secret: ${NAVER_SEARCH_CLIENT_SECRET}

app:
  baseUrl: https://ploggo.co.kr

file:
  upload-dir: /opt/ploggo/images
  badge-icon-dir: /opt/ploggo/badge-icons

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    operations-sorter: alpha
    oauth:
      client-id: ${KAKAO_CLIENT_ID}  # 카카오 클라이언트 ID
      use-pkce-with-authorization-code-grant: true
      additional-query-string-params:
        client_id: ${KAKAO_CLIENT_ID}
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match: /api/**
