name: auto-deploy-on-master-push
on:
  push:
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'build.gradle'
      - 'Dockerfile'
    branches:
      - master

# 권한 추가
permissions:
  contents: write
  packages: write

jobs:
  makeTagAndRelease:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.create_tag.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Create Tag
        id: create_tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.new_tag }}
          release_name: Release ${{ steps.create_tag.outputs.new_tag }}
          body: ${{ steps.create_tag.outputs.changelog }}
          draft: false
          prerelease: false
  buildImageAndPush:
    name: 도커 이미지 빌드와 푸쉬
    runs-on: ubuntu-latest
    needs: makeTagAndRelease
    steps:
      - uses: actions/checkout@v4
      - name: docker buildx 설치
        uses: docker/setup-buildx-action@v2
      - name: 레지스트리 로그인
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
        env:
          OWNER: '${{github.repository_owner}}'
#      - name: application-secret.yml 생성
#        env:
#          ACTIONS_STEP_DEBUG: true
#          APPLICATION_SECRET: ${{secrets.APPLICATION_SECRET}}
#        run: echo "$APPLICATION_SECRET" >> src/main/resources/application-secret.yml
#      - name: application-jwtTK.yml 생성
#        env:
#          ACTIONS_STEP_DEBUG: true
#          APPLICATION_JWTTK: ${{secrets.APPLICATION_JWTTK}}
#        run: echo "$APPLICATION_JWTTK" >> src/main/resources/application-jwtTK.yml
      - name: 빌드앤 푸쉬
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          no-cache: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/backend:${{ needs.makeTagAndRelease.outputs.tag_name }},
            ghcr.io/${{ env.OWNER_LC }}/backend:latest
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            docker stop swyp_web9th_team8_backend
            docker rm -f swyp_web9th_team8_backend
            docker pull ghcr.io/${{ env.OWNER_LC }}/backend:latest
            docker run --name swyp_web9th_team8_backend \
            --network app-network \
            --env-file /etc/environment \
            -p 8080:8080 \
            -d ghcr.io/${{ env.OWNER_LC }}/backend:latest
            docker image prune -f
